### ISSUE TITLE
Add Memcached support

### ISSUE THREAD

**Issue by bmonkman** [commitdev/zero-backend-node#42]
In the case where the user chose to enable Memcached caching, add some example code [similar to this](https://github.com/commitdev/zero-backend-node/blob/1376ac0e7ff4448d641633c0ff69f602acbeebf4/templates/src/app.js#L32) to test the connection to the Memcached server. 
The hostname and port can be exposed to the service through the environment variables `CACHE_ENDPOINT` and `CACHE_PORT` similar to [in the go backend](https://github.com/commitdev/zero-backend-go/blob/14c0f1a486989db66eaf045100c0184c6658607a/templates/kubernetes/base/kustomization.yml#L18-L21).
Probably using https://github.com/3rd-Eden/memcached

**Comment by kingsleytorlowei** [comment]
Is it okay to close this ticket?

**Comment by bmonkman** [comment]
Yep, thanks!
